[package]
name = "jason"
version = "0.1.0"
authors = ["Felipe Rosa <felipe.sgrosa@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"

[dev-dependencies]
tungstenite = "0.11.1"
url = "2.2.0"